### ISSUE TITLE
Error when updating to Laravel 5.2

### ISSUE THREAD

**Issue by xKairu** [cartalyst/sentinel#170]
```
vagrant@homestead:~/Projects/MyApp$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Generating autoload files
> php artisan clear-compiled
PHP Fatal error:  Uncaught ReflectionException: Class sentinel does not exist in /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
Stack trace:
#0 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('sentinel')
#1 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('sentinel', Array)
#2 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('sentinel', Array)
#3 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(1170): Illuminate\Foundation\Application->make('sentinel')
#4 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(151): Illuminate\Container\Container->offsetGet('sentinel')
#5 /home/vagrant/Projects/MyApp/vendor/laravel/framew in /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736
PHP Fatal error:  Uncaught ReflectionException: Class sentinel does not exist in /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
Stack trace:
#0 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('sentinel')
#1 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('sentinel', Array)
#2 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('sentinel', Array)
#3 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(1170): Illuminate\Foundation\Application->make('sentinel')
#4 /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(151): Illuminate\Container\Container->offsetGet('sentinel')
#5 /home/vagrant/Projects/MyApp/vendor/laravel/framew in /home/vagrant/Projects/MyApp/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736
```

**Comment by brunogaspar** [comment]
Can't reproduce this on a fresh Laravel 5.2 install.

Seems an error on your application.

**Comment by matfish2** [comment]
I am getting the same error in L5.1 after changing the default MailServiceProvider

**Comment by matfish2** [comment]
I am getting the same error on L6

**Comment by matfish2** [comment]
For anyone who encounters this issue later on. This is probably NOT a sentinel issue. What happens is that an exception is thrown early in the bootstrapping process before `sentinel` is bound to the IOC container. Look at the exception trace to find the exact breaking point (e.g in my case it was the exception handler)
