### ISSUE TITLE
Error in Laravel APIs and ThrottlesRequests

### ISSUE THREAD

**Issue by enprixd** [cartalyst/sentinel#416]
I'm encountering a bug in Laravel during tests where Illuminate's ThrottlesRequest Middleware tries to call the getAuthIdentifier in the user at $request->user() but instead there's an empty EloquentUser object that Cartalyst might have put there by default.

`[2018-02-02 13:56:40] testing.ERROR: Call to undefined method Illuminate\Database\Query\Builder::getAuthIdentifier() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Illuminate\\Database\\Query\\Builder::getAuthIdentifier() at /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2471)
[stacktrace]
#0 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1284): Illuminate\\Database\\Query\\Builder->__call('getAuthIdentifi...', Array)
#1 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1470): Illuminate\\Database\\Eloquent\\Builder->__call('getAuthIdentifi...', Array)
#2 /home/vagrant/code/some-project/vendor/cartalyst/sentinel/src/Users/EloquentUser.php(443): Illuminate\\Database\\Eloquent\\Model->__call('getAuthIdentifi...', Array)
#3 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(91): Cartalyst\\Sentinel\\Users\\EloquentUser->__call('getAuthIdentifi...', Array)
#4 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(47): Illuminate\\Routing\\Middleware\\ThrottleRequests->resolveRequestSignature(Object(Illuminate\\Http\\Request))
#5 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), '60', '1')
#6 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#7 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#9 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#10 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#11 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#12 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#13 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#14 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#29 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(345): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#30 /home/vagrant/code/some-project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(195): Illuminate\\Foundation\\Testing\\TestCase->call('POST', '/orders', Array, Array, Array, Array)
#31 /home/vagrant/code/some-project/tests/Feature/Api/OrdersControllerTest.php(379): Illuminate\\Foundation\\Testing\\TestCase->post('/orders', Array, Array)
#32 [internal function]: Tests\\Feature\\Api\\OrdersControllerTest->only_valid_coupons_should_be_accepted()
#33 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/Framework/TestCase.php(1071): ReflectionMethod->invokeArgs(Object(Tests\\Feature\\Api\\OrdersControllerTest), Array)
#34 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/Framework/TestCase.php(939): PHPUnit\\Framework\\TestCase->runTest()
#35 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/Framework/TestResult.php(698): PHPUnit\\Framework\\TestCase->runBare()
#36 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/Framework/TestCase.php(894): PHPUnit\\Framework\\TestResult->run(Object(Tests\\Feature\\Api\\OrdersControllerTest))
#37 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\\Framework\\TestCase->run(Object(PHPUnit\\Framework\\TestResult))
#38 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#39 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#40 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(546): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#41 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\\TextUI\\TestRunner->doRun(Object(PHPUnit\\Framework\\TestSuite), Array, true)
#42 /home/vagrant/code/some-project/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\\TextUI\\Command->run(Array, true)
#43 /home/vagrant/code/some-project/vendor/phpunit/phpunit/phpunit(53): PHPUnit\\TextUI\\Command::main()
#44 {main}
"} `

**Comment by enprixd** [comment]
This is a case of me not implementing the Authenticatable contract on my user object.

I apologize.
